
services:
  video-streaming:
    image: video-streaming-app
    build:
      context: ./
      dockerfile: Dockerfile
    
    ports:
     - "0:80"
    environment:
      - PORT=80
    restart: "no"   
  db:
    image: mongo:7.0.0
    container_name: db
    ports:
     - "27017:27017"
    restart: always     
