apiVersion: v1
kind: Service
metadata:
  name: video-streaming
spec:
  selector:
    app: video-streaming
  type: NodePort  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
    nodePort: 30000
